//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichHoc()
        {
            this.LichHoc_LopHocPhan = new HashSet<LichHoc_LopHocPhan>();
            this.LichHoc_NhomThucHanh = new HashSet<LichHoc_NhomThucHanh>();
        }
    
        public int ID_LichHoc { get; set; }
        public string NgayHoc { get; set; }
        public string TietHoc { get; set; }
        public string ID_PhongHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHoc_LopHocPhan> LichHoc_LopHocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHoc_NhomThucHanh> LichHoc_NhomThucHanh { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
